#spring:
#  profiles:
#    include: credential

server:
  port: 8080
aws:
  region: "ap-northeast-2"
  dynamodb:
    endpoint: ${dynamodbEndpoint}
    accessKey: ${awsAccessKey}
    secretKey: ${awsSecretKey}
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /




